name: ogp
description: OGP.app.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.0+4
  provider: ^4.0.4
  share: ^0.6.3+6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
